# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
title = "BlackLotus - Cybersecurity Portfolio"
baseURL = "https://your-domain.com/"  # Update when you deploy
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"                    # /tags/web-exploitation/
  category = "categories"         # /categories/red-team/
  author = "authors"              # /authors/blacklotus/
  series = "series"               # /series/htb-machines/
  platform = "platforms"         # /platforms/hack-the-box/
  difficulty = "difficulties"    # /difficulties/easy/
  technique = "techniques"        # /techniques/privilege-escalation/

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "platforms"
        weight = 80

    [[related.indices]]
        name = "techniques"
        weight = 70

    [[related.indices]]
        name = "difficulties"
        weight = 60

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10