# Home
[[main]]
name = "Home"
pageRef = "/"
weight = 1

# Writeups - Main section landing page
[[main]]
identifier = "writeups"
name = "Writeups"
pageRef = "writeups"
weight = 2

# Blue Team Labs - Parent menu item
[[main]]
identifier = "blue-team-labs"
name = "Blue Team Labs"
pageRef = "writeups/blue-team-labs"
parent = "writeups"
weight = 10

# Blue Team subsections
[[main]]
identifier = "defense"
name = "Defense"
pageRef = "writeups/blue-team-labs/defense"
parent = "blue-team-labs"
weight = 11

[[main]]
identifier = "forensics"
name = "Forensics"
pageRef = "writeups/blue-team-labs/forensics"
parent = "blue-team-labs"
weight = 12

# Red Team CTFs - Parent menu item
[[main]]
identifier = "red-team-ctfs"
name = "Red Team CTFs"
pageRef = "writeups/red-team-ctfs"
parent = "writeups"
weight = 20

# Red Team subsections
[[main]]
identifier = "hack-the-box"
name = "Hack The Box"
pageRef = "writeups/red-team-ctfs/hack-the-box"
parent = "red-team-ctfs"
weight = 21

[[main]]
identifier = "proving-grounds"
name = "Proving Grounds"
pageRef = "writeups/red-team-ctfs/proving-grounds"
parent = "red-team-ctfs"
weight = 22

[[main]]
identifier = "virtual-hacking-labs"
name = "Virtual Hacking Labs"
pageRef = "writeups/red-team-ctfs/virtual-hacking-labs"
parent = "red-team-ctfs"
weight = 23

[[main]]
identifier = "vulnlab"
name = "VulnLab"
pageRef = "writeups/red-team-ctfs/vulnlab"
parent = "red-team-ctfs"
weight = 24

# Templates section (if you want it in main menu)
# [[main]]
# identifier = "templates"
# name = "Templates"
# pageRef = "templates"
# weight = 100

# External links
[[main]]
identifier = "github"
name = "GitHub"
pre = "github" # icon 
url = "https://github.com/Yelodash"
weight = 200

[[main]]
identifier = "linkedin"
name = "LinkedIn"
pre = "linkedin" # icon 
url = "https://www.linkedin.com/in/moustapha-antoine-mindaoudou-6123311a3/"
weight = 205

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#[[footer]]
#name = "Changelog"
#pageRef = "changelog"
#weight = 10


