# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.

colorScheme = "Congo"  # Good choice! Also try "Slate" or "Terminal" for cyber aesthetic
defaultAppearance = "dark" # Perfect for cybersecurity
autoSwitchAppearance = true  # Let users choose

enableSearch = true
enableCodeCopy = true  # IMPORTANT: Enable code copying for your commands!

# Add your contact info
#replyByEmail = true  # Enable if you want contact functionality

# Better image handling for your screenshots
disableImageOptimization = false
disableImageOptimizationMD = false
backgroundImageWidth = 1200

# Add a default featured image for social sharing
defaultFeaturedImage = "images/cybersec-banner.jpg" # Add your cybersec banner
defaultSocialImage = "images/social-share.png" # For Twitter/LinkedIn previews

# Better TOC handling
smartTOC = true
smartTOCHideUnfocusedChildren = true

[params]
  contentWidth = "prose"  # or "max-w-4xl"

  
[header]
  layout = "fixed" # Keep this - good for navigation

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false  # Remove "Powered by Blowfish" for cleaner look
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"  # CHANGE THIS! Much better for portfolios
  homepageImage = "images/cybersec-hero.jpg" # Add a cybersecurity hero image
  showRecent = true  # Show your latest writeups
  showRecentItems = 6  # Show more recent posts
  showMoreLink = false
  showMoreLinkDest = "/writeups/"
  cardView = true  # Enable card view for better presentation

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true  # Show when you updated writeups
  showAuthor = true
  showHero = true
  heroStyle = "big"  # CHANGE: Bigger hero images for impact
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true  # Show tags and categories
  showAuthorsBadges = false
  showWordCount = false
  # Enable sharing for your writeups
  #sharingLinks = ["linkedin","github"]
  showZenMode = true  # Add focus mode for reading

[list]
  #showHero = true
  #heroStyle = "background"  # Nice background effect
  showBreadcrumbs = true
  showSummary = true  # IMPORTANT: Show summaries on cards
  showCards = true
  orderByWeight = true  # Custom ordering
  groupByYear = false  # Don't group by year for better flow
  cardView = true
  constrainItemsWidth = true

# Keep the rest as-is...

# Add this to your params.toml file